version: "3"
volumes:
  app_node_modules:
services:
  app:
    build: .
    user: "node"
    volumes:
      - ./:/home/node/app
      - app_node_modules:/home/node/app/node_modules/
    ports:
      - "3000:80"




