# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  deploy:
    working_directory: ~/
    docker:
      - image: node:8
    steps:
      - checkout
      - run:
          name: Installing deployment dependencies
          working_directory: ~/
          command: |
            apt-get -y -qq update
            apt-get -y install python-pip python-dev build-essential
            pip install awsebcli --upgrade

      - run:
          name: Deploying
          command: eb deploy prod-env
workflows:
  version: 2
  build:
    jobs:
      - deploy:
          filters:
            branches:
              only:
                - master